export const FETCH_COMPOSITION_REQUESTED = 'FETCH_COMPOSITION_REQUESTED'
export const FETCH_COMPOSITION_SUCCEEDED = 'FETCH_COMPOSITION_SUCCEEDED'
export const FETCH_COMPOSITION_FAILED = 'FETCH_COMPOSITION_FAILED'