export const FETCH_ENVIRONMENT_REQUESTED = 'FETCH_ENVIRONMENT_REQUESTED'
export const FETCH_ENVIRONMENT_SUCCEEDED = 'FETCH_ENVIRONMENT_SUCCEEDED'
export const FETCH_ENVIRONMENT_FAILED = 'FETCH_ENVIRONMENT_FAILED'

export function fetchEnvironmentRequested() {
  return {
    type: FETCH_ENVIRONMENT_REQUESTED
  }
}